version: "3.7"
services:
        pgsql:
                build: .
                restart: always
                container_name: pgsql
                hostname: pgsql
                network_mode: "bridge"
                environment: 
                        - BANCO_ENV=dev
                ports:
                        - 5432:5432
                volumes:
                        - ${HOME}/dev/servers/databases/postgresql/data:/var/lib/postgresql/data

        
